const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let recordContext={}, recordMeta=null, recordMounts=[];
let mode='transcript', entries=[], rows=[], request=0, audioURL=null, stopAt=null;
async function api(path, options){const response=await fetch(path,options);const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data;}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,3500);}
function time(ms){return ms==null?'Unknown':`${(ms/1000).toFixed(3)}s`;}
async function loadCorpus(){const ticket=++request;$('#results').innerHTML='<div class="empty">Finding passages…</div>';try{const data=await api('/api/corpus?'+new URLSearchParams({...recordContext,q:$('#query').value,mode,partial:$('#partial').checked}));if(ticket!==request)return;rows=data.rows;$('#segment-count').textContent=data.total;$('#translation-count').textContent=data.translated;$('#result-count').textContent=rows.length;$('#source-label').textContent=data.record?.record_id||data.source.split('/').pop();applyRecord(data.record||{});renderCorpus();}catch(error){if(ticket===request)$('#results').innerHTML=`<div class="empty">${escape(error.message)} <button class="text-button" id="retry">Try again</button></div>`;$('#retry')?.addEventListener('click',loadCorpus);}}
function renderCorpus(){ $('#results').innerHTML=rows.length?rows.map((r,i)=>`<article class="passage"><div class="passage-top"><span class="time">${escape(r.timestamp)} — ${escape(r.end_timestamp)}</span><span>${escape(r.participant)} · ${escape(r.annotation_id)}</span></div><div class="passage-body"><div><div class="label">ORIGINAL LANGUAGE</div><div class="transcript">${escape(r.transcript)}</div></div><div><div class="label">${escape(recordMeta?.translations?.find(t=>t.id===recordContext.translation)?.label||"TRANSLATION")}</div><div class="translation ${r.translation?'':'empty-translation'}">${escape(r.translation||'Translation not yet documented')}</div></div></div><div class="passage-footer"><button class="text-button" data-play="${i}">▷ Listen to segment</button><button class="text-button" data-add="${i}">+ Collect a word</button></div><details><summary>Annotation details · ${r.morphemes.length} morpheme annotations</summary>${Object.entries(r.associated_annotations).map(([tier,items])=>`<div class="label" style="margin-top:12px">${escape(tier)}</div>${items.map(x=>`<div class="child"><strong>${escape(x.text||'Empty annotation')}</strong> <span class="muted">${escape(x.annotation_id)} · ${time(x.start_ms)} – ${time(x.end_ms)}</span></div>`).join('')}`).join('')}</details></article>`).join(''):'<div class="empty"><h2>No matching passages</h2><p>Try another word, switch the language, or enable “Match within words”.</p></div>'; }
async function loadBank(){entries=await api('/api/lexicon');$('#bank-count').textContent=entries.length;$('#word-count').textContent=entries.length;renderBank();}
function renderBank(){const q=$('#bank-query').value.toLocaleLowerCase();const filtered=entries.filter(e=>(e.word+' '+e.meaning).toLocaleLowerCase().includes(q));$('#lexicon-results').innerHTML=filtered.length?filtered.map(e=>`<article class="entry"><div class="entry-top"><div><h3>${escape(e.word)}</h3><p>${escape(e.meaning||'Meaning to be documented')}${e.part_of_speech?' · '+escape(e.part_of_speech):''}</p></div><button class="text-button" data-edit="${escape(e.word)}">Edit entry</button></div>${e.notes?`<p>${escape(e.notes)}</p>`:''}<details><summary>${e.examples.length} saved example${e.examples.length===1?'':'s'}</summary>${e.examples.map(x=>`<blockquote><div class="transcript">${escape(x.transcript)}</div><p>${escape(x.translation||'Translation not yet documented')}</p><small>${time(x.start_ms)} – ${time(x.end_ms)} · ${escape(x.annotation_id)} · ${escape(x.source_file.split('/').pop())}</small></blockquote>`).join('')||'<p>No corpus examples yet.</p>'}</details></article>`).join(''):`<div class="empty"><h2>${entries.length?'No matching words':'Your next discovery belongs here.'}</h2><p>${entries.length?'Try another word or meaning.':'Add a word from the corpus. Its examples will come along with it.'}</p><button class="primary" id="empty-add">+ Add a word</button></div>`;$('#empty-add')?.addEventListener('click',()=>openEditor());}
function openEditor(word=''){const form=$('#entry-form');form.reset();$('#save-error').textContent='';const existing=entries.find(e=>e.word.normalize('NFC').toLowerCase()===word.normalize('NFC').toLowerCase());for(const key of ['word','meaning','notes','part_of_speech'])form.elements[key].value=existing?.[key]??(key==='word'?word:'');$('#editor').showModal();form.elements.word.focus();}
$('.tabs').addEventListener('click',event=>{const button=event.target.closest('[data-mode]');if(!button)return;mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b===button));loadCorpus();});
$('#search-form').addEventListener('submit',e=>{e.preventDefault();loadCorpus();});$('#partial').addEventListener('change',loadCorpus);$('#clear').addEventListener('click',()=>{$('#query').value='';loadCorpus();});
$('nav').addEventListener('click',e=>{const button=e.target.closest('[data-page]');if(!button)return;const page=button.dataset.page;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b===button));for(const name of ['corpus','lexicon','labels','volume'])$('#'+name+'-page').hidden=name!==page;const titles={volume:['Volume','Bring your files into view.','Connect local and cloud storage to your language workspace.'],corpus:['Corpus explorer','Every word has a story.','Explore the language in context. Find a phrase, follow its sound, keep what you discover.'],lexicon:['My lexicon','A language, word by word.','Build a living lexicon, grounded in the examples you discover.'],labels:['Labeling workspace','Find the patterns between words.','Compare passages, subtract what you know, and review what remains.']};$('#breadcrumb').textContent=titles[page][0];$('#title').textContent=titles[page][1];$('#subtitle').textContent=titles[page][2];$('#new-entry').hidden=page==='volume';$('.stats').hidden=page==='volume';if(page==='labels')loadLabels();setRecordsOpen(page==='corpus');if(page==='corpus')loadRecords();setSourcesOpen(page==='volume');if(page==='volume')loadVolumes();});
$('#new-entry').addEventListener('click',()=>openEditor());$('#close-dialog').addEventListener('click',()=>$('#editor').close());$('#bank-query').addEventListener('input',renderBank);$('#lexicon-results').addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(b)openEditor(b.dataset.edit);});
$('#results').addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){const selected=window.getSelection().toString().trim();openEditor(selected||(mode==='transcript'?$('#query').value.trim():''));return;}const play=e.target.closest('[data-play]');if(play){if(!audioURL){toast('Load the matching audio recording first.');$('#audio-file').click();return;}const r=rows[+play.dataset.play];if(r.start_ms==null||r.end_ms==null){toast('This segment has no complete timing.');return;}const player=$('#player');if(player.readyState===0){toast('The recording is still loading. Try again shortly.');return;}if(r.start_ms/1000>=player.duration){toast('This interval is outside the loaded recording.');return;}player.currentTime=r.start_ms/1000;stopAt=r.end_ms/1000;player.play().catch(()=>toast('The recording could not be played.'));}});
$('#audio-file').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const player=$('#player');player.pause();stopAt=null;if(audioURL)URL.revokeObjectURL(audioURL);audioURL=URL.createObjectURL(file);player.src=audioURL;player.hidden=false;$('#audio-status').textContent='Loaded: '+file.name+' · Segment playback uses EAF timestamps.';});$('#player').addEventListener('timeupdate',()=>{if(stopAt!==null&&$('#player').currentTime>=stopAt){$('#player').pause();stopAt=null;}});$('#player').addEventListener('error',()=>toast('This audio file could not be decoded. Try a WAV or MP3 recording.'));
$('#entry-form').addEventListener('submit',async e=>{e.preventDefault();$('#save-entry').disabled=true;$('#save-error').textContent='';try{const body=Object.fromEntries(new FormData(e.target));body.context=recordContext;const entry=await api('/api/lexicon',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('#editor').close();await loadBank();toast(`Saved ${entry.word} with ${entry.examples.length} examples.`);}catch(error){$('#save-error').textContent=error.message;}finally{$('#save-entry').disabled=false;}});
loadCorpus();loadBank().catch(error=>{$('#lexicon-results').textContent=error.message;toast('Could not load the lexicon.');});

let labelData=null;
async function loadLabels(){ $('#label-results').innerHTML='<div class="empty">Comparing translated passages…</div>';try{labelData=await api('/api/labels?'+new URLSearchParams(recordContext));$('#label-summary').textContent=`${labelData.translated_passages} translated passages · ${labelData.seed_count} single-word lexicon seeds · ${labelData.suggestions.length} repeated original-language words`;renderLabels();}catch(e){$('#label-results').textContent=e.message;}}
function renderLabels(){if(!labelData)return;const query=$('#label-query').value.normalize('NFC').toLowerCase();const list=labelData.suggestions.filter(x=>x.word.includes(query));$('#label-results').innerHTML=list.map(p=>`<article class="entry"><div class="entry-top"><div><div class="label">ORIGINAL-LANGUAGE WORD · ${p.support} PASSAGES · ${p.translated_support} TRANSLATED</div><h3>${escape(p.word)}</h3></div><span class="label-status ${p.status}">${escape({'single-candidate':'One shared candidate',ambiguous:'Multiple possibilities',insufficient:'Needs more translations',unresolved:'No shared candidate','lexicon-supported':'In the lexicon'}[p.status])}</span></div><p>${p.shared.length?'Portuguese words shared across translated examples: '+p.shared.map(escape).join(' · '):'No Portuguese word is shared across the translated examples. Review the evidence below.'}</p><div class="candidate-list">${p.candidates.map(c=>`<div class="candidate"><div><strong>${escape(c.word)}</strong><div class="muted">${c.support}/${c.total} translated examples · ${c.outside} other translated passages</div></div><button class="text-button" data-confirm-word="${escape(p.word)}" data-confirm-target="${escape(c.word)}">Review label →</button></div>`).join('')}</div><details><summary>Show the sentence equations & evidence</summary>${p.evidence.map(e=>`<blockquote><small>${escape(e.id)} · ${escape(e.timestamp)}</small><div class="transcript">${escape(e.transcript)}</div><p>${escape(e.translation||"Translation not documented — excluded from candidate comparison")}</p><div class="equation">Remaining Portuguese words: ${e.remaining.map(escape).join(' + ')||'none'}</div>${Object.keys(e.removed).length?`<p class="muted">Subtracted using lexicon: ${Object.entries(e.removed).map(([a,b])=>escape(a)+' = '+escape(b)).join('; ')}</p>`:''}</blockquote>`).join('')}</details></article>`).join('')||'<div class="empty">No repeated original-language words match this filter. At least two translated passages are required.</div>';}
$('#label-query').addEventListener('input',renderLabels);$('#refresh-labels').addEventListener('click',loadLabels);
let pendingLabel=null;
$('#label-results').addEventListener('click',e=>{const b=e.target.closest('[data-confirm-word]');if(!b)return;pendingLabel={word:b.dataset.confirmWord,meaning:b.dataset.confirmTarget};$('#label-confirm-text').textContent=`Confirm “${pendingLabel.word}” as “${pendingLabel.meaning}”?`;$('#label-confirm-error').textContent='';$('#label-confirm').showModal();});
$('#cancel-label').addEventListener('click',()=>$('#label-confirm').close());
$('#accept-label').addEventListener('click',async()=>{$('#accept-label').disabled=true;try{await api('/api/labels/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...pendingLabel,context:recordContext})});$('#label-confirm').close();await loadBank();await loadLabels();toast('Label added to the lexicon. Suggestions recomputed.');}catch(e){$('#label-confirm-error').textContent=e.message;}finally{$('#accept-label').disabled=false;}});

let volumeProvider='local', volumes=[], activeVolume=null, volumeFolder='', volumeCursor=null, volumeItems=[], volumeRequest=0;
const postVolume=(action,body)=>api('/api/volumes/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
$('.provider-grid').addEventListener('click',e=>{const b=e.target.closest('[data-provider]');if(!b)return;volumeProvider=b.dataset.provider;document.querySelectorAll('[data-provider]').forEach(p=>{const selected=p===b;p.classList.toggle('selected',selected);p.setAttribute('aria-pressed',String(selected));});for(const provider of ['local','s3','azure']){const field=$('#'+provider+'-fields');field.hidden=provider!==volumeProvider;field.disabled=provider!==volumeProvider;}$('#volume-form-title').textContent={local:'Mount a local folder',s3:'Mount an S3 bucket',azure:'Mount an Azure container'}[volumeProvider];$('#volume-error').textContent='';});
async function loadVolumes(){try{volumes=await api('/api/volumes');$('#volume-count').textContent=volumes.length;$('#volume-list').innerHTML=volumes.length?volumes.map(v=>`<article class="entry"><div class="entry-top"><div><div class="label">${escape({local:'LOCAL FOLDER',s3:'AMAZON S3',azure:'AZURE BLOB STORAGE'}[v.provider])}</div><h3>${escape(v.name)}</h3><p class="volume-path">${escape(v.location)}</p><p class="muted">Access checked ${escape(new Date(v.verified_at).toLocaleString())}</p></div><div><button class="primary" data-browse-volume="${escape(v.id)}">Browse files</button><button class="text-button" data-unmount-volume="${escape(v.id)}">Unmount</button></div></div></article>`).join(''):'<div class="empty"><h2>No volumes mounted yet</h2><p>Choose a location above to connect your first volume.</p></div>';renderSourceRoots();}catch(e){$('#volume-list').textContent=e.message;$('#source-tree').textContent=e.message;}}
$('#volume-form').addEventListener('submit',async e=>{e.preventDefault();const fields=Object.fromEntries(new FormData(e.target));fields.provider=volumeProvider;fields.prefix=fields[volumeProvider+'_prefix']||'';delete fields.s3_prefix;delete fields.azure_prefix;$('#mount-volume').disabled=true;$('#mount-volume').textContent='Checking connection…';$('#volume-error').textContent='';try{const result=await postVolume('mount',fields);await loadVolumes();toast('Volume mounted: '+result.volume.name);setSourcesOpen(true);await expandMountedSource(result.volume.id);}catch(error){$('#volume-error').textContent=error.message;}finally{$('#mount-volume').disabled=false;$('#mount-volume').textContent='Test & mount volume';}});
$('#refresh-volumes').addEventListener('click',loadVolumes);
$('#volume-list').addEventListener('click',async e=>{const browse=e.target.closest('[data-browse-volume]');const unmount=e.target.closest('[data-unmount-volume]');if(browse){activeVolume=volumes.find(v=>v.id===browse.dataset.browseVolume);setSourcesOpen(true);expandMountedSource(activeVolume.id);}if(unmount){unmount.disabled=true;try{await postVolume('unmount',{id:unmount.dataset.unmountVolume});if(activeVolume?.id===unmount.dataset.unmountVolume){activeVolume=null;volumeRequest++;}await loadVolumes();toast('Volume unmounted. Files remain in place.');}catch(error){toast(error.message);unmount.disabled=false;}}});
function fileSize(size){if(size==null)return 'Folder';if(size<1024)return size+' B';if(size<1048576)return (size/1024).toFixed(1)+' KB';return (size/1048576).toFixed(1)+' MB';}

$('#choose-local-folder').addEventListener('click',async()=>{const button=$('#choose-local-folder');button.disabled=true;$('#mount-volume').disabled=true;$('#volume-error').textContent='';$('#folder-picker-status').textContent='Choose a folder in the macOS dialog. It may appear behind the browser.';try{const result=await postVolume('choose-folder',{});if(result.path){$('#local-folder-path').value=result.path;const name=$('#volume-form').elements.name;if(!name.value.trim())name.value=result.path.replace(/\/$/,'').split('/').pop()||'Local volume';$('#folder-picker-status').textContent='Folder selected. Use Test & mount volume to connect.';}else{$('#folder-picker-status').textContent='Selection cancelled. Your existing path was kept.';}}catch(error){$('#volume-error').textContent=error.message;$('#folder-picker-status').textContent='You can also enter a folder path manually.';}finally{button.disabled=false;$('#mount-volume').disabled=false;}});

let treeGeneration=0, documentRequest=0, documentURL=null;
function setSourcesOpen(open){document.body.classList.toggle('sources-open',open);$('#sources-panel').inert=!open;}
function renderSourceRoots(){treeGeneration++;$('#source-tree').innerHTML='';if(!volumes.length){$('#source-tree').innerHTML='<div class="empty">Mount a location to see its files here.</div>';return;}for(const v of volumes){const node=makeFolder(v.id,'',v.name);node.dataset.rootId=v.id;const meta=document.createElement('div');meta.className='muted source-provider';meta.textContent={local:'Local folder',s3:'Amazon S3',azure:'Azure Blob Storage'}[v.provider];node.insertBefore(meta,node.lastChild);$('#source-tree').append(node);}}
function makeFolder(id,path,name){const node=document.createElement('div');node.className='source-folder';const button=document.createElement('button');button.type='button';button.className='source-toggle';button.setAttribute('aria-expanded','false');button.textContent='▸ ▱ '+name;button.title=path||name;const children=document.createElement('div');children.className='source-children';children.hidden=true;node.append(button,children);let loaded=false;button.addEventListener('click',async()=>{const open=children.hidden;children.hidden=!open;button.setAttribute('aria-expanded',String(open));button.textContent=(open?'▾':'▸')+' ▱ '+name;if(open&&!loaded){loaded=true;await loadTreeChildren(id,path,children,null);}});return node;}
async function loadTreeChildren(id,path,container,cursor){const generation=treeGeneration;const loading=document.createElement('span');loading.className='muted';loading.textContent='Loading…';container.append(loading);try{const result=await postVolume('browse',{id,folder:path,cursor});if(generation!==treeGeneration)return;loading.remove();if(!result.items.length&&!cursor){const empty=document.createElement('div');empty.className='muted';empty.textContent='Empty folder';container.append(empty);}for(const item of result.items){if(item.folder)container.append(makeFolder(id,item.path,item.name));else{const button=document.createElement('button');button.type='button';button.className='source-file';button.textContent='▤ '+item.name;button.title=item.name+' · '+fileSize(item.size);button.addEventListener('click',()=>openDocument(id,item.path,button));container.append(button);}}if(result.next_cursor){const more=document.createElement('button');more.className='text-button';more.textContent='Load more';more.addEventListener('click',()=>{more.remove();loadTreeChildren(id,path,container,result.next_cursor);});container.append(more);}}catch(error){loading.textContent=error.message;const retry=document.createElement('button');retry.className='text-button';retry.textContent='Retry';retry.addEventListener('click',()=>{retry.remove();loading.remove();loadTreeChildren(id,path,container,cursor);});container.append(retry);}}
async function expandMountedSource(id){const root=Array.from($('#source-tree').children).find(n=>n.dataset.rootId===id);if(root){const button=root.querySelector('button');if(button.getAttribute('aria-expanded')==='false')button.click();}}
async function openDocument(id,path,button){const ticket=++documentRequest;document.querySelectorAll('.source-file').forEach(b=>b.classList.toggle('selected',b===button));$('#document-preview').hidden=false;$('#document-title').textContent=path.split('/').pop();$('#document-location').textContent=(volumes.find(v=>v.id===id)?.name||'Volume')+' / '+path;$('#document-content').textContent='Opening document…';$('#document-preview').scrollIntoView({behavior:'smooth',block:'start'});if(documentURL){URL.revokeObjectURL(documentURL);documentURL=null;}try{const data=await postVolume('open',{id,path});if(ticket!==documentRequest)return;const content=$('#document-content');content.textContent='';if(data.kind==='text'){const pre=document.createElement('pre');pre.className='document-text';pre.textContent=data.text;content.append(pre);}else{const bytes=Uint8Array.from(atob(data.data),c=>c.charCodeAt(0));documentURL=URL.createObjectURL(new Blob([bytes],{type:data.mime}));let view;if(['image/png','image/jpeg','image/gif','image/webp'].includes(data.mime)){view=document.createElement('img');view.alt=data.name;view.src=documentURL;}else if(data.mime==='application/pdf'){view=document.createElement('iframe');view.title=data.name;view.src=documentURL;}else if(data.mime.startsWith('audio/')){view=document.createElement('audio');view.controls=true;view.src=documentURL;}if(view){view.className='document-media';content.append(view);}else{const p=document.createElement('p');p.textContent='Download this document to open it in its usual application.';content.append(p);}const link=document.createElement('a');link.href=documentURL;link.download=data.name;link.textContent='Download '+data.name;content.append(link);}}catch(error){if(ticket===documentRequest)$('#document-content').textContent=error.message;}}
$('#close-document').addEventListener('click',()=>{documentRequest++;$('#document-preview').hidden=true;$('#document-content').textContent='';if(documentURL){URL.revokeObjectURL(documentURL);documentURL=null;}});
$('#close-sources').addEventListener('click',()=>setSourcesOpen(false));$('#refresh-sources').addEventListener('click',loadVolumes);

// Compact record navigation directly beside the primary sidebar.
function setRecordsOpen(open){document.body.classList.toggle('records-open',open);$('#records-panel').inert=!open;}
async function loadRecords(){try{recordMounts=await api('/api/records');renderRecords();}catch(e){$('#record-tree').textContent=e.message;}}
function renderRecords(){const query=$('#record-filter').value.toLowerCase();$('#record-tree').innerHTML='';for(const mount of recordMounts){const group=document.createElement('section');const heading=document.createElement('h3');heading.className='label';heading.textContent=mount.name;group.append(heading);if(mount.error){const p=document.createElement('p');p.className='muted';p.textContent=mount.error;group.append(p);}for(const record of mount.records.filter(r=>r.record_id.toLowerCase().includes(query))){const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent=record.record_id;summary.title=record.record_id;summary.className='record-name';details.append(summary);const files=document.createElement('div');files.className='record-child-files';details.append(files);summary.addEventListener('click',()=>{if(!details.open){selectRecord(mount.id,record.record_id);loadRecordFiles(mount.id,record.record_id,files);}});group.append(details);}if(!mount.records.length){const p=document.createElement('p');p.className='muted';p.textContent='No record folders. Use one top-level folder per record_id.';group.append(p);}$('#record-tree').append(group);}if(!recordMounts.length)$('#record-tree').innerHTML='<p class="muted">Mount a folder in Volume to browse records.</p>';}
async function loadRecordFiles(id,record,container){container.textContent='Loading…';try{const page=await postVolume('browse',{id,folder:record});container.textContent='';for(const item of page.items){const b=document.createElement('button');b.className='source-file';b.textContent=(item.folder?'▱ ':'▤ ')+item.name;b.title=item.name;b.addEventListener('click',()=>{if(item.path.toLowerCase().endsWith('.eaf'))selectRecord(id,record,{eaf:item.path});else showRecordFile(id,item.path,item.folder);});container.append(b);}if(page.next_cursor){const note=document.createElement('p');note.className='muted';note.textContent='More files available in Volume.';container.append(note);}}catch(e){container.textContent=e.message;}}
async function showRecordFile(id,path,isFolder){if(isFolder){toast('Browse nested folders in Volume. Record assets belong directly inside the record folder.');return;}$('#record-document-title').textContent=path.split('/').pop();$('#record-document-text').textContent='Opening…';$('#record-document').showModal();try{const data=await postVolume('open',{id,path});$('#record-document-text').textContent=data.kind==='text'?data.text:'Use the audio selector for recordings, or Volume to preview this file.';}catch(e){$('#record-document-text').textContent=e.message;}}
function resetRecording(){const player=$('#player');player.pause();player.removeAttribute('src');player.load();player.hidden=false;if(audioURL?.startsWith('blob:'))URL.revokeObjectURL(audioURL);audioURL=null;stopAt=null;}
async function selectRecord(volume_id,record_id,extra={}){request++;resetRecording();recordMeta=null;recordContext={volume_id,record_id,...extra};$('#query').value='';$('#record-name').textContent=record_id;$('#record-files').textContent='Loading record…';await loadCorpus();}
function setOptions(selector,options,value){const select=$(selector);select.innerHTML='';for(const item of options){const option=document.createElement('option');option.value=item.id;option.textContent=item.label;select.append(option);}select.value=value||'';select.disabled=options.length<2;}
function applyRecord(meta){if(!meta.record_id){$('#record-controls-placeholder')?.remove();return;}const changed=!recordMeta||recordMeta.volume_id!==meta.volume_id||recordMeta.record_id!==meta.record_id;recordMeta=meta;recordContext={volume_id:meta.volume_id,record_id:meta.record_id,eaf:meta.eaf,tier:meta.tier,translation:meta.translation};$('#record-name').textContent=meta.record_id;setOptions('#record-eaf',meta.eafs.map(id=>({id,label:id.split('/').pop()})),meta.eaf);setOptions('#record-tier',meta.transcript_tiers.map(id=>({id,label:id})),meta.tier);setOptions('#record-translation',meta.translations.length?meta.translations:[{id:'',label:'No translation tier'}],meta.translation);$('#record-files').textContent=meta.files.map(f=>f.name).join(' · ');if(changed){setOptions('#record-audio',meta.audio.map(a=>({id:a.url,label:a.name})),meta.audio[0]?.url);if(meta.audio.length){audioURL=meta.audio[0].url;$('#player').src=audioURL;$('#player').hidden=false;$('#audio-status').textContent=meta.audio[0].name;}else{resetRecording();$('#audio-status').textContent='No audio file found in this record folder.';}}}
$('#record-eaf').addEventListener('change',()=>{recordContext.eaf=$('#record-eaf').value;delete recordContext.tier;delete recordContext.translation;loadCorpus();});$('#record-tier').addEventListener('change',()=>{recordContext.tier=$('#record-tier').value;delete recordContext.translation;loadCorpus();});$('#record-translation').addEventListener('change',()=>{recordContext.translation=$('#record-translation').value;loadCorpus();});$('#record-audio').addEventListener('change',()=>{resetRecording();audioURL=$('#record-audio').value;$('#player').src=audioURL;$('#audio-status').textContent=$('#record-audio').selectedOptions[0]?.textContent||'';});
$('#record-filter').addEventListener('input',renderRecords);$('#refresh-records').addEventListener('click',loadRecords);$('#close-records').addEventListener('click',()=>setRecordsOpen(false));$('#expand-records').addEventListener('click',()=>{const wide=document.body.classList.toggle('records-wide');$('#expand-records').setAttribute('aria-expanded',String(wide));$('#expand-records').setAttribute('aria-label',wide?'Compact record browser':'Expand record browser');});
$('#record-audio-slot').append($('#audio-status'),$('#player'));$('#close-record-document').addEventListener('click',()=>$('#record-document').close());
